version: "3.9"

services:
  mariadb:
    image: "mariadb"
    restart: always
    ports: 
    - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
  redis:
    image: "redis"
    restart: always
    ports: 
    - "${REDIS_PORT}:6379"
    volumes:
      - ./config:/data
    command: redis-server --appendonly yes
  palila:
    build: .
    links: 
     - mariadb
     - redis
    env_file:
      - .env
    environment:
      - MARIADB_PORT=3306
      - REDIS_PORT=6379
    volumes:
      - ./files:/usr/bot/files
      - ./cache:/usr/bot/cache
      - ./log:/usr/bot/log
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started